const data = {
  products: [
    {
      name: 'Nike Running Shoes',
      slug: 'nike-running-shoes',
      category: 'Running',
      image: '/images/s1.jpg',
      price: 115,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      name: 'Adidas Road Sneakers Shoes',
      slug: 'adidas-sneakers-shoes',
      category: 'Sneakers',
      image: '/images/s2.jpg',
      price: 88,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 5,
      description: 'very comforatble',
    },
    {
      name: 'Puma Running Shoes',
      slug: 'puma-running-shoes',
      category: 'Running',
      image: '/images/s3.jpg',
      price: 75,
      countInStock: 3,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 4,
      description: 'economic choice',
    },
    {
      name: 'Li-Ning Road Sneakers Shoes',
      slug: 'li-ning-sneakers-shoes',
      category: 'Sneaker',
      image: '/images/s4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      description: 'latest version',
    },
    {
      name: 'Nike Road Running Shoes',
      slug: 'nikerunning-shoes',
      category: 'Running',
      image: '/images/s5.jpg',
      price: 150,
      countInStock: 9,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 6,
      description: 'newer release',
    },
    {
      name: 'Nike Road Sneakers Shoes',
      slug: 'nikesneakers-shoes',
      category: 'Sneaker',
      image: '/images/s6.jpg',
      price: 119,
      countInStock: 3,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'light and flexible',
    },
  ],
};
export default data;
